// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwV4zBBvSI9ZaymZtcoDylwttfFLPfPRM',
    appId: '1:256208024072:web:b394795f96be79a93bd7bd',
    messagingSenderId: '256208024072',
    projectId: 'travelbuddy-68fba',
    authDomain: 'travelbuddy-68fba.firebaseapp.com',
    storageBucket: 'travelbuddy-68fba.appspot.com',
    measurementId: 'G-K09PD2N2X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KJYgC71qBOzl6T8tNH60BXrZYllAOPo',
    appId: '1:256208024072:android:8dbd72e763fa88ff3bd7bd',
    messagingSenderId: '256208024072',
    projectId: 'travelbuddy-68fba',
    storageBucket: 'travelbuddy-68fba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLyIRJ5StprauPOeko179h5qtumjMjNmU',
    appId: '1:256208024072:ios:98044cb0f67676423bd7bd',
    messagingSenderId: '256208024072',
    projectId: 'travelbuddy-68fba',
    storageBucket: 'travelbuddy-68fba.appspot.com',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLyIRJ5StprauPOeko179h5qtumjMjNmU',
    appId: '1:256208024072:ios:98044cb0f67676423bd7bd',
    messagingSenderId: '256208024072',
    projectId: 'travelbuddy-68fba',
    storageBucket: 'travelbuddy-68fba.appspot.com',
    iosBundleId: 'com.example.travelBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwV4zBBvSI9ZaymZtcoDylwttfFLPfPRM',
    appId: '1:256208024072:web:0a0036e93190e1cb3bd7bd',
    messagingSenderId: '256208024072',
    projectId: 'travelbuddy-68fba',
    authDomain: 'travelbuddy-68fba.firebaseapp.com',
    storageBucket: 'travelbuddy-68fba.appspot.com',
    measurementId: 'G-6LXXTW8F9W',
  );
}
